# Generated by Django 3.2.4 on 2021-06-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210613_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='bv',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='cmp',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='cpe',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='date',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='der',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps1',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps2',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps3',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps4',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps5',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps6',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps7',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps8',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='eps9',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='fcf',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='ipe',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe1',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe2',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe3',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe4',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe5',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe6',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe7',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe8',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe9',
        ),
    ]
