# Generated by Django 3.2.4 on 2021-06-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210614_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='epsgr',
        ),
    ]
