# Generated by Django 3.2.4 on 2021-06-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210614_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='f_eps',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
