# Generated by Django 3.2.4 on 2021-06-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_companies_f_eps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='f_eps',
            new_name='psr',
        ),
    ]
