# Generated by Django 3.2.4 on 2021-06-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_f_eps_companies_psr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='psr',
            new_name='sales',
        ),
    ]
