# Generated by Django 3.2.4 on 2021-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_psr_companies_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='market_cap',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
