# Generated by Django 3.2.4 on 2021-06-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_companies_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='ipe',
        ),
    ]
