# Generated by Django 3.2.4 on 2021-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_companies_ipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='ipe',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
