# Generated by Django 3.2.4 on 2021-06-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_companies_ipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='pe2',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe3',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe4',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe5',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe6',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe7',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe8',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pe9',
        ),
    ]
