# Generated by Django 3.2.4 on 2021-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210616_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='pe2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe3',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe4',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe5',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe6',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe7',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe8',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pe9',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
